<?php

namespace think\addons\command;

use think\addons\Service;
use think\console\Input;
use think\console\Output;
use think\facade\Config;
use think\console\Command;
use think\console\input\Option;
use think\helper\Arr;

class SendService extends Command
{
    public function configure()
    {
        $this->setName('addons:service')
            ->setDescription('Publish addons service to global service');
    }

    public function execute(Input $input, Output $output)
    {
        $systemServicePath= $this->app->getAppPath() . 'service.php';
        // 发送服务
        $publishService = 'think\\addons\\Service';
        $services = [];
        if(is_file($systemServicePath)){
            $originService = include $systemServicePath;
            $services = $originService ?: [];
            if(in_array($publishService, $originService)){
                $this->output->info("Addons Service exist!");
                return true;
            }else{
                array_push($services, $publishService);
            }
        }else{
            $services[] = 'think\\addons\\Service';
        }

        $header = '// This file is automatically generated at:' . date('Y-m-d H:i:s') . PHP_EOL . 'declare (strict_types = 1);' . PHP_EOL;

        $content = '<?php ' . PHP_EOL . $header . "return " . var_export($services, true) . ';';

        file_put_contents($systemServicePath, $content);

        $output->writeln('<info>Succeed!</info>');
    }
}