<?php

namespace think\addons\command;

use think\addons\Service;
use think\console\Input;
use think\console\Output;
use think\facade\Config;
use think\console\Command;
use think\console\input\Option;
use think\helper\Arr;

class SendService extends Command
{
    /**
     * 重写 service:discover 自动添加服务到系统服务
     */
    public function configure()
    {
        $this->setName('service:discover')
            ->setDescription('Discover Services for ThinkPHP');
    }

    public function execute(Input $input, Output $output)
    {
        // 原始程序的发布服务
        if (is_file($path = $this->app->getRootPath() . 'vendor/composer/installed.json')) {
            $packages = json_decode(@file_get_contents($path), true);
            // Compatibility with Composer 2.0
            if (isset($packages['packages'])) {
                $packages = $packages['packages'];
            }

            $services = [];
            foreach ($packages as $package) {
                if (!empty($package['extra']['think']['services'])) {
                    $services = array_merge($services, (array) $package['extra']['think']['services']);
                }
            }

            $header = '// This file is automatically generated at:' . date('Y-m-d H:i:s') . PHP_EOL . 'declare (strict_types = 1);' . PHP_EOL;

            $content = '<?php ' . PHP_EOL . $header . "return " . var_export($services, true) . ';';

            file_put_contents($this->app->getRootPath() . 'vendor/services.php', $content);

            $output->writeln('<info>Succeed!</info>');
        }

        // 更新 addons service 服务
        $systemServicePath= $this->app->getAppPath() . 'service.php';
        // 发送服务
        $publishService = 'think\\addons\\Service';
        $services = [];
        if(is_file($systemServicePath)){
            $originService = include $systemServicePath;
            $services = $originService ?: [];
            if(in_array($publishService, $originService)){
                $this->output->info("Addons Service exist!");
                return true;
            }else{
                array_push($services, $publishService);
            }
        }else{
            $services[] = 'think\\addons\\Service';
        }

        $header = '// This file is automatically generated at:' . date('Y-m-d H:i:s') . PHP_EOL . 'declare (strict_types = 1);' . PHP_EOL;

        $content = '<?php ' . PHP_EOL . $header . "return " . var_export($services, true) . ';';

        file_put_contents($systemServicePath, $content);

        $output->writeln('<info>Succeed!</info>');
    }
}